"""
05_predict.py
Inference pipeline: run blocking on test data, compute features, apply trained model.

Produces:
  - output/matching_results.tsv   (leaderboard submission)
  - output/candidate_pairs.tsv    (blocking candidates for audit)
"""

import os
import sys
import pickle
import logging
import argparse
import numpy as np
import pandas as pd
from tqdm import tqdm

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(BASE_DIR, 'src'))

from preprocess_utils import preprocess_dataframe
from features import FEATURE_COLS, build_feature_matrix, build_lookups, expand_candidates

logging.basicConfig(level=logging.INFO, format='%(asctime)s %(levelname)s %(message)s')
log = logging.getLogger(__name__)


def run_prediction(
    split: str,
    data_dir: str,
    models_dir: str,
    output_dir: str,
    threshold: float = None,
):
    """
    Run full inference for a given split.
    
    Args:
        split: 'test' or 'train' (for validation scoring)
        data_dir: path to dataset/
        models_dir: path to models/
        output_dir: path to output/
        threshold: override threshold (if None, loads from models/best_threshold.txt)
    """
    os.makedirs(output_dir, exist_ok=True)

    # ── Load trained model ──
    model_path = os.path.join(models_dir, 'lgbm_model.pkl')
    thresh_path = os.path.join(models_dir, 'best_threshold.txt')

    log.info(f"Loading model from {model_path} ...")
    with open(model_path, 'rb') as f:
        model = pickle.load(f)

    if threshold is None:
        with open(thresh_path, 'r') as f:
            threshold = float(f.read().strip())
    log.info(f"Using decision threshold: {threshold:.4f}")

    # ── Load preprocessed data (from blocking cache or regenerate) ──
    cache_path = os.path.join(models_dir, f'{split}_preprocessed.pkl')
    if os.path.exists(cache_path):
        log.info(f"Loading preprocessed data from cache: {cache_path}")
        with open(cache_path, 'rb') as f:
            cache = pickle.load(f)
        s1  = cache['s1']
        s23 = cache['s23']
    else:
        log.info("No cache found, preprocessing from raw files...")
        prefix = f"{split}_source"
        data_split_dir = os.path.join(data_dir, split)
        s1_raw = pd.read_csv(os.path.join(data_split_dir, f'{prefix}1.tsv'), sep='\t', dtype=str).fillna('')
        s2_raw = pd.read_csv(os.path.join(data_split_dir, f'{prefix}2.tsv'), sep='\t', dtype=str).fillna('')
        s3_raw = pd.read_csv(os.path.join(data_split_dir, f'{prefix}3.tsv'), sep='\t', dtype=str).fillna('')

        s1  = preprocess_dataframe(s1_raw)
        s2  = preprocess_dataframe(s2_raw)
        s3  = preprocess_dataframe(s3_raw)
        s23 = pd.concat([s2, s3], ignore_index=True)

    # ── Load candidate pairs ──
    # candidate_pairs.tsv should have been generated by blocking step for this split
    cand_file = os.path.join(output_dir, 'candidate_pairs.tsv')
    if not os.path.exists(cand_file):
        log.error(f"candidate_pairs.tsv not found at {cand_file}. Run blocking first.")
        raise FileNotFoundError(cand_file)

    log.info(f"Loading candidates from {cand_file} ...")
    cand_df = pd.read_csv(cand_file, sep='\t', dtype=str).fillna('')

    # ── Expand candidates to pairs ──
    pairs_df = expand_candidates(cand_df)
    log.info(f"Expanded to {len(pairs_df):,} candidate pairs for inference")

    if len(pairs_df) == 0:
        log.warning("No candidate pairs found! Check blocking output.")
        # Write empty outputs
        _write_outputs(s1, {}, output_dir, split)
        return

    # ── Build lookups ──
    log.info("Building entity lookup dicts...")
    s1_lookup, s23_lookup = build_lookups(s1, s23)

    # ── Compute features in batches ──
    log.info("Computing pairwise features...")
    feat_df = build_feature_matrix(
        pairs_df[['source1_entity_id', 'candidate_entity_id']],
        s1_lookup,
        s23_lookup
    )

    # ── Model inference ──
    log.info("Running model inference...")
    X = feat_df[FEATURE_COLS].values.astype(np.float32)
    probs = model.predict_proba(X)[:, 1]
    feat_df['prob'] = probs
    feat_df['match'] = probs >= threshold

    log.info(f"Predicted {feat_df['match'].sum():,} matches out of {len(feat_df):,} candidates "
             f"(threshold={threshold:.4f})")

    # ── Build matching results ──
    matched = (
        feat_df[feat_df['match']]
        .groupby('source1_entity_id')['candidate_entity_id']
        .apply(lambda x: ','.join(sorted(set(x))))
        .reset_index()
    )
    matched.columns = ['source1_entity_id', 'matched_entity_ids']

    # Ensure every S1 entity has a row
    s1_ids_df = pd.DataFrame({'source1_entity_id': s1['entity_id'].tolist()})
    results_df = s1_ids_df.merge(matched, on='source1_entity_id', how='left')
    results_df['matched_entity_ids'] = results_df['matched_entity_ids'].fillna('')

    # ── Write outputs ──
    suffix = f'_{split}' if split != 'test' else ''

    results_path = os.path.join(output_dir, f'matching_results{suffix}.tsv')
    results_df.to_csv(results_path, sep='\t', index=False)
    log.info(f"Written matching_results to {results_path}")

    # Stats
    non_empty = results_df[results_df['matched_entity_ids'] != '']
    singletons = len(results_df) - len(non_empty)
    total_matches = non_empty['matched_entity_ids'].apply(lambda x: len(x.split(','))).sum()
    log.info(f"Results: {len(non_empty):,} entities with matches, "
             f"{singletons:,} singletons, {total_matches:,} total match links")

    return results_df, feat_df


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--split', default='test', choices=['train', 'test'])
    parser.add_argument('--data-dir',   default=os.path.join(BASE_DIR, 'dataset'))
    parser.add_argument('--models-dir', default=os.path.join(BASE_DIR, 'models'))
    parser.add_argument('--output-dir', default=os.path.join(BASE_DIR, 'output'))
    parser.add_argument('--threshold',  type=float, default=None)
    args = parser.parse_args()

    run_prediction(args.split, args.data_dir, args.models_dir, args.output_dir, args.threshold)
